<?php echo $this->render('header.phtml'); ?>
<body>
<div id="pageContent">
    <div class="contain-to-grid header_nav">
        <nav class="top-bar" data-topbar>
            <ul class="title-area">
                <!-- Title Area -->
                <li class="name">
                    <h1><a class="aTitle" href="<?php echo $this->domainLink(1); ?>">UO</a></h1>
                </li>
                <li class="toggle-topbar menu-icon"><a href="#"><span><?php echo __('menu') ?></span></a></li>
            </ul>

            <section class="top-bar-section">
                <ul class="nav-bar">
                    <?php echo $this->siteMenu(); ?>
                </ul>
            </section>
        </nav>
    </div>
    <!-- #wrapper -->
    <?php
    echo isset($this->page->title) ? $this->pageTitle(false, $this->page->title) : $this->pageTitle(false, $this->header);
    ?>
    <section class="section_light">
        <div class="row full-height">
            <!-- #content-->
            <?php echo $this->layout()->content; ?>
        </div>
    </section>
</div>
<?php
echo $this->render('footer.phtml');
?>
</body>
</html>