<div class="row">
    <?php echo $this->notification($this->service); ?>
    <div class="medium-6 columns">
        <div class="columns panel">
            <?php
            echo $this->form;
            ?>
        </div>
    </div>
    <div class="medium-6 columns">
        <div class="columns panel">
            <h3>
                <?php echo __('writeUs'); ?>
            </h3>

            <p>
                <?php echo __('textForWriteUs'); ?>
            </p>

            <p>
                <?php
                $mime     = "image/png";
                $image    = imageFromText($this->email, 200, 20);
                $imageSrc = "data:" . $mime . ";base64," . $image;
                ?>
                <?php echo __('email'); ?>: <img class="contactAddress" src="<?php echo $imageSrc ?>">
            </p>
        </div>
    </div>
</div>
