<?php
echo $this->notification($this->service);

$tableUserProfile = $this->partial(
    'index/partials/_userProfile.phtml',
    ['profileDetails' => $this->profileDetails]
);

$tableUserTransactions = $this->partial(
    'index/partials/_userTransactions.phtml',
    ['profileDetails' => $this->profileDetails]
);

$box = '';
$box = '<div class="row large-8">' .
    '<div class="section-container auto" data-section="auto" data-options="deep-linking: true;">';

$box
    .= '<section>
            <p class="title" data-section-title><a href="#userProfile">' . __('userProfile') . '</a></p>
            <div class="content" data-slug="userProfile" data-section-content>
                ' . $tableUserProfile . '
            </div>
        </section>';

$box
    .= '<section>
            <p class="title" data-section-title><a href="#userTransactions">' . __('financialInfo') . '</a></p>
            <div class="content" data-slug="userTransactions" data-section-content>
                ' . $this->box($tableUserTransactions) . '
            </div>
        </section>
      </div>
     </div>';

echo $box;