<?php
$vacancyBlock = '<div class="vacanciesContainer">';
$host         = $this->domainLink(null, true);
if (empty($this->vacancies)) {
    echo __('noVacancies');
} else {
    $messages = MessagesAccess::getAddNewMessages($this->vacancies->getIds(), MessagesAccess::VACANCY_TYPE);
    foreach ($this->vacancies as $v) {
        $editLink      = $host . 'management/edit/ad/vacancy/id/' . $v->vacancyId;
        $deleteLink    = $host . 'management/delete/ad/vacancy/id/' . $v->vacancyId;
        $publishLink   = $host . 'management/publish/ad/vacancy/id/' . $v->vacancyId;
        $unpublishLink = $host . 'management/unpublish/ad/vacancy/id/' . $v->vacancyId;
        $messagesLink  = $this->domainLink(1, true) . 'profile/index/messages/vid/' . $v->vacancyId;

        $vacancyTemplate = '<div class="vacancyBlock">
    <div class="vacancyHead clearfix" id="v_h_Id_%d">
        <div class="vacancySeat">%s</div>
        <div class="vacancyDate visible-for-medium-up">%s</div>
        <div class="vacancyActions">
            <ul class="button-group">%s</ul>
        </div>
    </div>
    <div class="vacancyInformation hideElem clearfix" id="v%d"">
        <div class="vacancyInnerInfo">
            <ul class="small-block-grid-1 medium-block-grid-3 large-block-grid-3">
                <li><h3 class="fdU">%s</h3>
                    <hr class="adHr">
                    <p>%s</p></li>
                <li><h3 class="fdU">%s</h3>
                    <hr class="adHr">
                    <p>%s</p></li>
                <li><h3 class="fdU">%s</h3>
                    <hr class="adHr">
                    <p>%s</p></li>
            </ul>
            <h3 class="fdU">%s</h3>
            <hr class="adHr">
            %s
        </div>
        <div class="vacancyDateStatus right">
            <p class="visible-for-small-down"><span class="fdU">%s</span>: %s</p>
            <p><span class="fdU">%s</span>: %s</p>
        </div>
    </div>
</div>';

        $iconButtons = $this->iconButton('', 'plus pl10', __('open'), 'v_plus_Id_' . $v->vacancyId, 'fs20 plus');
        $iconButtons .= $this->iconButton(
            '',
            'minus pl10',
            __('close'),
            'v_minus_Id_' . $v->vacancyId,
            'fs20 minus hideElem'
        );
        $iconButtons .= $this->iconButton(
            $editLink,
            'pencil pl10',
            __('editVacancy'),
            'v_edit_Id_' . $v->vacancyId,
            'fs20 edit-vacancy'
        );
        if ((int)$v->isPublished) {
            $iconButtons .= $this->iconButton(
                $unpublishLink,
                'lightbulb pl10',
                __('published'),
                'v_publish_Id_' . $v->vacancyId,
                'fs20 unpublish'
            );
        } else {
            $iconButtons .= $this->iconButton(
                $publishLink,
                'prohibited pl10',
                __('unpublished'),
                'v_unpublish_Id_' . $v->vacancyId,
                'fs20 publish'
            );
        }
        if ((int)$v->isBanned) {
            $iconButtons .= $this->iconButton(
                '',
                'dislike pl10',
                __('notApproved'),
                'v_banned_Id_' . $v->vacancyId,
                'banned fs20'
            );
        } else {
            $iconButtons .= $this->iconButton(
                '',
                'like pl10',
                __('approved'),
                'v_unbanned_Id_' . $v->vacancyId,
                'banned fs20'
            );
        }
        $iconButtons .= $this->iconButton(
            $deleteLink,
            'page-delete pl10',
            __('deleteAd'),
            'v_delete_Id_' . $v->vacancyId,
            'fs20 delete'
        );

        $count = isset($messages[$v->vacancyId]) ? $messages[$v->vacancyId] : 0;
        $iconButtons .= $this->iconButton(
            $messagesLink,
            'mail pl10',
            __('messages') . '(' . $count . ')',
            'messages_' . $v->vacancyId,
            'mail fs20',
            '',
            '<span class="fs14 messagesCount">(' . $count . ')</span>'
        );

        if (!empty($v->tags)) {
            $tags      = $v->tags->getItems();
            $tagsBlock = '<ul class="pl10 tags">';
            foreach ($tags as $t) {
                $tagsBlock .= '<li class="post-tag"><span class="tag">' . $t->tagName . '</span></li>';
            }
            $tagsBlock .= '</ul>';
        }

        $vacancyBlock .= sprintf(
            $vacancyTemplate,
            $v->vacancyId,
            $v->seat,
            '(' . __('createdAt') . ': ' . date('Y-m-d', strtotime($v->createdAt)) . ')',
            $iconButtons,
            $v->vacancyId,
            __('requirements'),
            $v->requirements,
            __('vacancyDescription'),
            $v->vacancyDescription,
            __('offer'),
            $v->offer,
            __('tags'),
            $tagsBlock,
            __('createdAt'),
            date('Y-m-d', strtotime($v->createdAt)),
            __('published'),
            $this->type($v->isPublished, 'boolean')
        );
    }
    $vacancyBlock .= '</div>';
    echo $vacancyBlock;
}

