<?php
echo $this->reveal(
    '<div class="small-10">' . __('delete_row_message') . '</div>',
    'dialog-delete',
    'small',
    'delete-button-confirm'
);
echo $this->reveal(
    '<div class="small-10">' . __('areYouSureToPublish') . '</div>',
    'dialog-publish',
    'small',
    'publish-button-confirm'
);
echo $this->reveal(
    '<div class="small-10">' . __('areYouSureToUnpublish') . '</div>',
    'dialog-unpublish',
    'small',
    'unpublishButtonConfirm'
);
echo $this->reveal(
    '<div class="small-10">' . $this->service->getVacancyForm() . '</div>',
    'dialog-edit-vacancy',
    'large'
);
echo $this->reveal(
    '<div class="small-10">' . $this->service->getResumeForm() . '</div>',
    'dialog-edit-resume',
    'large'
);