<?php
$form = $this->service->getEmailTemplateForm();
?>

<script type="text/javascript">

    var container = '<?php echo $this->container ?>';
    var closeButtonName = "<?php echo $this->translation('close')?>";
    $(document).on('focusin', function (e) {
        if ($(event.target).closest(".mce-window").length) {
            e.stopImmediatePropagation();
        }
    });
    $(document).ready(function () {
        var spinnerLink = "<?php echo $this->domainLink(1) . 'images/ajax-loader.gif'; ?>";

        $().ajaxModalUrl({
            clickClass: ".delete-" + container,
            modalWindowId: "#delete",
            height: 300,
            width: 400,
            useClickHref: true,
            closeButtonName: closeButtonName,
            spinnerLink: spinnerLink,
            submitButtonSelector: '.delete-button-confirm',
            reload: true
        });

        $().ajaxModalFormSubmitter({
            clickObj: ".edit-" + container,
            modalWindowId: "#form-" + container,
            closeButtonName: closeButtonName,
            spinnerLink: spinnerLink,
            formId: "form#" + '<?php echo $form->getId()?>',
            width: 400,
            height: 300,
            useClickUrl: true,
            editor: true,
            isHTMLEditor: true,
            editorElementId: "mailBody"

        });

        $().ajaxModalFormSubmitter({
            clickObj: "#add-" + container,
            modalWindowId: "#form-" + container,
            closeButtonName: closeButtonName,
            spinnerLink: spinnerLink,
            formId: "form#" + '<?php echo $form->getId()?>',
            width: 400,
            height: 300,
            useClickUrl: true,
            isHTMLEditor: true,
            editorElementId: "mailBody"
        });

    });
</script>
