<?php
$form = $this->service->getUploadForm();
?>

<script type="text/javascript">

    var container = '<?php echo $this->container ?>';
    var closeButtonName = "<?php echo $this->translation('close')?>";

    $('input#image').keyup(function () {
        var input = $(this).val();
        if ((input.length) >= 3) {
            $.ajax(
                {
                    url: "",
                    data: {word: input},
                    success: function (html, st) {

                    }
                });
        }

    })

    $(document).on('focusin', function (e) {
        if ($(event.target).closest(".mce-window").length) {
            e.stopImmediatePropagation();
        }
    });

    $(document).ready(function () {
        var spinnerLink = "<?php echo $this->domainLink(1) . 'images/ajax-loader.gif'; ?>";

        $().ajaxModalUrl({
            clickClass: ".remove-image",
            modalWindowId: "#dialog-delete",
            height: 300,
            width: 400,
            useClickHref: true,
            closeButtonName: closeButtonName,
            spinnerLink: spinnerLink,
            reload: true,
            submitButtonSelector: '.delete-button-confirm'
        });

        $().ajaxModalFormSubmitter({
            clickObj: ".edit-" + container,
            modalWindowId: '#dialog-edit',
            closeButtonName: closeButtonName,
            spinnerLink: spinnerLink,
            formId: "form#" + '<?php echo $form->getId()?>',
            width: 700,
            height: 550,
            useClickUrl: true
        });

        $().ajaxModalFormSubmitter({
            clickObj: "#upload-" + container,
            modalWindowId: '#dialog-upload',
            closeButtonName: closeButtonName,
            spinnerLink: spinnerLink,
            formId: "form#" + '<?php echo $form->getId()?>',
            width: 700,
            resetForm: false,
            height: 550,
            useClickUrl: true
        });

    });
</script>
