<div class="row">
    <div class="large-12 columns">
        <?php
        $lang = Zend_Registry::get('language');
        if (empty($this->pages)) {
            return false;
        }
        echo '<div class="blog">';
        foreach ($this->pages as $step => $p) {
            $date = new Zend_Date($p->dateCreated, 'y-M-d H:i:s');
            ?>
            <div class="row">
                <h6>
                    <a href="<?php echo $this->domainLink(1) . $lang . '/' . $p->slug . '.html' ?>"><?php echo $p->title ?></a>
                </h6>
                <span class="list-date"><?php echo $date->toString('dd/MM/yy') ?></span>

                <p>
                    <?php echo $p->shortContent ?>
                </p>
            </div>
        <?php } ?>
    </div>
</div>